{
 "title": "Ziraa Logs",
 "tags": [ "logging" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Error Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ziraa\", level=\"error\"}"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ziraa\", level=\"info\"} |= ``"
    }
   ]
  },
  {
   "title": "HTTP Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ziraa\", level=\"http\"}",
     "legendFormat": "Auto"
    }
   ]
  }
 ]
}